// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function StartBatch(arg1, arg2) {
  return window['go']['main']['App']['StartBatch'](arg1, arg2);
}

export function StartListening(arg1) {
  return window['go']['main']['App']['StartListening'](arg1);
}

export function StopBatch() {
  return window['go']['main']['App']['StopBatch']();
}

export function StopListening() {
  return window['go']['main']['App']['StopListening']();
}
