// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Send(arg1:string):Promise<void>;

export function StartBatch(arg1:Array<string>,arg2:number):Promise<void>;

export function StartListening(arg1:number):Promise<void>;

export function StopBatch():Promise<void>;

export function StopListening():Promise<void>;
